<!DOCTYPE html>
<html>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>FECOAGRO Leite Minas</title>

        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="<?php echo $this->basePath(); ?>/css/animate.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">

    </head>

    <body class="gray-bg">

        <div class="loginColumns animated fadeInDown">
            <div class="row">

                <div class="col-md-6">
                    <h2 class="font-bold">Fecoagro Leite Minas</h2>

                   
                </div>
                <div class="col-md-6">
                    
                    <?php if($this->erro) {?>
                        <div class="alert alert-danger">Usuário ou senha incorretos.</div>
                    <?php }?>
                    
                    <?php
                    $this->form->prepare();
                    $this->form->setAttribute('action', $this->url('login'));
                    ?>
                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    echo $this->formHidden($this->form->get('id'));
                    echo $this->formElement($this->form->get('csrf'));
                    ?>

                    <div class="ibox-content">

                        <div class="form-group">
                            <label>e-mail: </label>
                                <?php
                                echo $this->formInput($this->form->get('email'));
                                echo $this->formElementErrors()->render($this->form->get('email'));
                                ?>
                        </div>
                        <div class="form-group">

                            <label>Senha: </label>
                            <?php
                            echo $this->formInput($this->form->get('senha'));
                            echo $this->formElementErrors()->render($this->form->get('senha'));
                            ?>
                        </div>
                        <button type="submit" class="btn btn-primary block full-width m-b">Entrar</button>

                        <a href="<?php echo $this->url('login', array('action' => 'recuperar-senha'))?>">
                           <small>Recuperar Senha</small>
                        </a>


                        </form>

                    </div>
                </div>
            </div>
            <hr/>

        </div>

    </body>

</html>