<!DOCTYPE html>
<html>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Fecoagro Leite Minas</title>

        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="<?php echo $this->basePath(); ?>/css/animate.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">

    </head>

    <body class="gray-bg">

        <div class="loginColumns animated fadeInDown">
            <div class="row">

                <div class="col-md-6">
                    <h2 class="font-bold">Fecoagro Leite Minas</h2>

                

                </div>
                <div class="col-md-6">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="fundo-branco">
                            <?php echo $this->message(); ?>
                            <form name="cadastro" method="post" action="<?php echo $this->url('login', array('action' => 'recuperar-senha')) ?>" class="form-cadastro forms validacao_form">
                                
                                <?php echo $this->formElement($this->form->get('csrf')); ?>

                                <legend>Para recuperar sua senha, informe seu e-mail:</legend>

                                <div class="metade-left">
                                    <label for="TxtEmail">E-mail <span class="required">*</span></label>
                                    <?php
                                    echo $this->formInput($this->form->get('email'));
                                    echo $this->formElementErrors()->render($this->form->get('email'));
                                    ?>
                                </div>

                                <button type="submit" class="btn btn-success">Enviar</button>						
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr/>

        </div>

    </body>

</html>