        <div class="header-box-inner cover-fix" style="background-image: url('http://www.jonosake.com.br/images/banner_historia.jpg');">
            <div class="circle-line circle-line-bottom circle-line2"></div>
            <div class="container">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h1>NOSSA HISTÓRIA</h1>

                    <h3>Uma semente de esperança chamada Joaquim Inoue.</h3>
                </div>
            </div>
        </div>

        <div class="cta blue-bg clearfix">
            <div class="container clearfix">
                <div class="row-height">
                    <div class="col-md-8 white" style="text-align: justify">

                        <div class="col-md-12">

                            <h2>A ORIGEM</h2>
                        </div>
                        <div class="col-md-6">

                            Uma semente de esperança. uma semente chamada Joaquim Inoue, de origem japonesa, humilde,
                            casado com Dona Norma e pai de duas filhas, que pelas terras de Itaguaí, no Rio de Janeiro,
                            no início dos anos 80, resolveu comprar um sítio simples, para desfrutar dos fins de semana
                            com familiares e amigos. A ideia de uma possibilidade de negócio sobre seu terreno surgiu em
                            função do lazer. Tudo começou quando um amigo pediu para que o senhor Joaquim emprestasse o
                            sítio para um evento particular. Bom coração que sempre foi, não só emprestou o seu lar como
                            foi o churrasqueiro do evento, contando com a ajuda da própria família, tendo a esposa Norma
                            no comando da cozinha e suas filhas, Keiko e Sami, como garçonetes.<br>
                            Um dos convidados elogiou o atendimento da família e perguntou se ele poderia alugar também
                            para outro evento. E assim começou o primeiro atendimento oficial, para 20 pessoas.<br><br>

                            O casal Joaquim e Norma Inoue eram pessoas honestas, trabalhadoras, sócios e de um coração
                            enorme. Enquanto jovem, o senhor Joaquim era proprietário do único cinema da cidade de
                            Itaguaí, em que certa ocasião levou para cantar toda a Jovem Guarda. Quando falamos da Jovem
                            Guarda referimonos a todos os nomes, como Wanderléia, Erasmo Carlos, entre outros. Do
                            agenciamento desses shows nasceram amizades com personalidades do meio, como a que teve com
                            Roberto Carlos, que levou inclusive o jovem Joaquim Inoue a participar do filme “Diamante
                            Cor de Rosa”, juntamente com o cantor, como figurante.<br><br>


                        </div>
                        <div class="col-md-6">

                            A boa forma do senhor Joaquim se dava através da sua profissão, professor de Educação Física
                            da UFRRJ, a famosa universidade Rural. Em suas atividades participou de vários projetos como
                            a primeira versão do “Projeto Rondon”, além de projetos esportivos como passeios ciclísticos
                            para vários estados, tendo o seu trabalho reconhecido pelo projeto “Criança Esperança”, em
                            meados dos anos 80. Iniciou uma pequena escola chamada “Esporte para Todos” para crianças
                            carentes, em seu próprio sítio, começando apenas com dez alunos. Após cinco anos ele já
                            tinha cerca de mil crianças de toda a redondeza da Costa Verde e Zona Oeste, onde conseguiu
                            formar vários jogadores de voleibol, tênis, futebol de campo e nadadores, levando-os ao
                            campeonato do “Jornal dos Esportes”, onde foram campeões, derrotando a tão famosa equipedo
                            Bradesco. A Dona Norma, além de braço direito para tudo o que o seu esposo pensava, era
                            pedagoga e advogada. “Enquanto ele imaginava, ela já estava colocando os tijolos um sobre o
                            outro”, declara a filha Keiko.<br><br>

                            <h3 class="marginb-15">
                                "Quando recebemos o primeiro ônibus com 46 passageiros, quase não dormimos. Era uma
                                responsabilidade tamanha, pois o sítio não tinha sido projetado para este fim. hoje,
                                graças a Deus, podemos contar com um atendimento diário de até 2.000 pessoas."
                                <small>Keiko Taguti, filha do senhor Joaquim.</small>
                            </h3>


                        </div>

                        <div class="col-md-12">

                            <h2 class="marginb-15 text-center">
                                POR QUE O NOME JONOSAKE?<br>
                                <strong>JO</strong>aquim + <strong>NO</strong>rma + <strong>SA</strong>mi +
                                <strong>KE</strong>iko
                            </h2>
                        </div>

                    </div>

                    <div class="col-md-4">
                        <img src="http://www.jonosake.com.br/images/historia_1.jpg" class="img-responsive">
                        <img src="http://www.jonosake.com.br/images/historia_2.jpg" class="img-responsive margint-5">
                    </div>
                </div>
            </div>
        </div>
        <!-- END CTA -->
            <div class="section-info steps-section section-padding paddingt-0 row-height text-center clearfix">

                <!-- <div class="second-row clearfix">

                    
                    <script src="https://snapwidget.com/js/snapwidget.js"></script>
                    <iframe src="https://snapwidget.com/embed/383636" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>

                </div> -->


                <div class="first-row clearfix">
                    <div class="container">
                        <div class="row-height">
                            <div class="steps-info col-height col-md-12">
                                <!-- <h1>O SEU DIA É MAIS FELIZ AQUI!</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
