<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->titulo ?></h2>
    </div>
    <div class="col-lg-">
        <div class="ibox float-e-">

            <div class="ibox-">
                <div class="panel- col-lg-">

                    <?php if ($this->erro) { ?>
                        <div id="alert-message">
                            <div class="alert alert-danger alert-block fade in">
                                <button type="button" class="close" data-dismiss="alert">×</button>Verifique os erros.
                            </div>
                        </div>
                    <?php } ?>

                    <?php
                    $this->form->prepare();
                    if ($this->registro) {
                        $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'editar', 'id' => $this->registro->getId())));
                    } else {
                        $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'novo')));
                    }
                    ?>

                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    echo $this->formHidden($this->form->get('id'));
                    echo $this->formElement($this->form->get('csrf'));
                    ?>

                    <div class="panel blank-panel" >

                      
                        <div class="panel-body" style="margin-left: 15px">
                            <div class="tab-content">

                                <div class="tab-pane active" id="tab-1">

                                    <div class="form-group">
                                        <label>Mostrar no Site? </label>
                                        <?php
                                        echo $this->formCheckBox($this->form->get('status'));
                                        echo $this->formElementErrors()->render($this->form->get('status'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Região: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formSelect($this->form->get('regiao'));
                                        echo $this->formElementErrors()->render($this->form->get('regiao'));
                                        ?>
                                    </div>


                                    <div class="form-group">
                                        <label>Nome: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('nome'));
                                        echo $this->formElementErrors()->render($this->form->get('nome'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Posição: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('posicao'));
                                        echo $this->formElementErrors()->render($this->form->get('posicao'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Texto: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('texto'));
                                        echo $this->formElementErrors()->render($this->form->get('texto'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Endereço: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('endereco'));
                                        echo $this->formElementErrors()->render($this->form->get('endereco'));
                                        ?>
                                        <div class="alert alert-warning">
                                            Ex: "Rua Afonso Pena, 1000, Belo Horizonte-Mg
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <label>Imagem: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('imagem'));
                                        echo $this->formElementErrors()->render($this->form->get('imagem'));
                                        ?>
                                    </div>


                                    <div class="form-group">
                                        <label>Catálogo: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('catalogo'));
                                        echo $this->formElementErrors()->render($this->form->get('catalogo'));
                                        ?>
                                    </div>


                                    <div class="form-group permissao_add permissao_editar">
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                                name="salvar" value="1" style="margin-left: 15px">
                                            <strong>Salvar</strong>
                                        </button>
                                    </div>


                                </div>

                            </div>

                        </div>
                    </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
