<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">

            <h2><?php echo $this->titulo; ?></h2>

            <div class="ibox-content">

                <?php echo $this->message(); ?>

                <div class="text-right">
                    <a href="<?php echo $this->url($this->routeController, array('action' => 'novo')); ?>" class="btn btn-success permissao_add"> <i class="fa fa-plus"></i> Adicionar </a>
                </div>

                <div class="table-responsive margem_table_lista">
                    <?php if (!$this->registros) { ?>       
                        <div class="alert alert-warning alert-dismissable">
                            <i class="fa fa-warning"></i> Sua busca não encontrou nenhum resultado.
                        </div>
                    <?php } ?>
                    
                    <form method="post" action="<?php echo $this->url($this->routeController, array('action' => 'fila')); ?>">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Título</th>
                                <th style="text-align: center">Imagem</th>
                                <th>Ação</th>  
                            </tr>
                        </thead>

                        <tbody>
                            <?php foreach ($this->registros as $item) { ?>
                                
                                <tr>

                                    <td>
                                        <?php 
                                            $enviado = $item->getEnviado();
                                            if(!$enviado)
                                        {?>
                                            <input type="checkbox" name="item[]" value="<?php echo $item->getId(); ?>">
                                        <?php } else {?>
                                            Enviada
                                        <?php }?>
                                    </td>

                                    <td>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>">
                                            <?php echo $item->getNome(); ?>
                                        </a>
                                    </td>
                                    
                                    
                                    <td align="center">

                                        <?php if (!empty($item->getImagem())) { ?>
                                        <img src="/gestao/bloco-home/imagem?image=noticias/<?php echo $item->getImagem(); ?>&x=150&y=150" style="border-radius: 5px"> 
                                        <?php } ?>

                                    </td>    
                                    <td>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>" class="btn btn-xs btn-default permissao_remover"><span class="glyphicon glyphicon-pencil"></span></a>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'remover', 'id' => $item->getId())); ?>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <button class="btn btn-sm btn-primary m-t-n-xs" type="submit"
                                            name="salvar" value="1" style="margin-left: 15px">
                                        <strong>Enviar newsletter</strong>
                                    </button>
                    </form>
                    <?php
                    echo $this->paginationControl($this->registros, 'Sliding', 'partial/paginator', array('route' => $this->routeController));
                    ?>


                </div>
               
            </div>
        </div>
    </div>

</div>