<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agenda extends \Usuario\Entity\Agenda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'descricao', 'nucleo_agenda', 'perfil_agenda', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'created_at', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'data', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'data_cancelamento', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'enviado', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'publico', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'texto');
        }

        return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'descricao', 'nucleo_agenda', 'perfil_agenda', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'created_at', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'data', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'data_cancelamento', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'enviado', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'publico', '' . "\0" . 'Usuario\\Entity\\Agenda' . "\0" . 'texto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agenda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublico', array());

        return parent::getPublico();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublico($publico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublico', array($publico));

        return parent::setPublico($publico);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function addNucleoAgenda(\Usuario\Entity\NucleoAgenda $NucleoAgenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNucleoAgenda', array($NucleoAgenda));

        return parent::addNucleoAgenda($NucleoAgenda);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNucleoAgenda(\Usuario\Entity\NucleoAgenda $NucleoAgenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNucleoAgenda', array($NucleoAgenda));

        return parent::removeNucleoAgenda($NucleoAgenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getNucleoAgenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNucleoAgenda', array());

        return parent::getNucleoAgenda();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerfilAgenda(\Usuario\Entity\PerfilAgenda $PerfilAgenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerfilAgenda', array($PerfilAgenda));

        return parent::addPerfilAgenda($PerfilAgenda);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerfilAgenda(\Usuario\Entity\PerfilAgenda $PerfilAgenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerfilAgenda', array($PerfilAgenda));

        return parent::removePerfilAgenda($PerfilAgenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfilAgenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfilAgenda', array());

        return parent::getPerfilAgenda();
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', array());

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMes', array());

        return parent::getMes();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data_uso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data_uso));

        return parent::setData($data_uso);
    }

    /**
     * {@inheritDoc}
     */
    public function data($tipo, $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'data', array($tipo, $date));

        return parent::data($tipo, $date);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnviado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnviado', array());

        return parent::getEnviado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnviado($enviado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnviado', array($enviado));

        return parent::setEnviado($enviado);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', array());

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto($texto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', array($texto));

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCancelamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCancelamento', array());

        return parent::setDataCancelamento();
    }

}
