<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Documento extends \Usuario\Entity\Documento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'categoria', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'nome', 'nucleo_documento', 'perfil_documento', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'created_at', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'data_cancelamento', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'enviado', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'texto');
        }

        return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'categoria', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'nome', 'nucleo_documento', 'perfil_documento', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'created_at', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'data_cancelamento', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'enviado', '' . "\0" . 'Usuario\\Entity\\Documento' . "\0" . 'texto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Documento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function addNucleoDocumento(\Usuario\Entity\NucleoDocumento $NucleoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNucleoDocumento', array($NucleoDocumento));

        return parent::addNucleoDocumento($NucleoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNucleoDocumento(\Usuario\Entity\NucleoDocumento $NucleoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNucleoDocumento', array($NucleoDocumento));

        return parent::removeNucleoDocumento($NucleoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNucleoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNucleoDocumento', array());

        return parent::getNucleoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerfilDocumento(\Usuario\Entity\PerfilDocumento $PerfilDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerfilDocumento', array($PerfilDocumento));

        return parent::addPerfilDocumento($PerfilDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerfilDocumento(\Usuario\Entity\PerfilDocumento $PerfilDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerfilDocumento', array($PerfilDocumento));

        return parent::removePerfilDocumento($PerfilDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfilDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfilDocumento', array());

        return parent::getPerfilDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnviado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnviado', array());

        return parent::getEnviado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnviado($enviado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnviado', array($enviado));

        return parent::setEnviado($enviado);
    }

    /**
     * {@inheritDoc}
     */
    public function data($tipo, $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'data', array($tipo, $date));

        return parent::data($tipo, $date);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', array());

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto($texto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', array($texto));

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCancelamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCancelamento', array());

        return parent::setDataCancelamento();
    }

}
