        <div class="header-box-inner cover-fix" style="background-image: url('http://www.jonosake.com.br/images/banner_contato.jpg');">
            <div class="circle-line circle-line-bottom circle-line2"></div>
            <div class="container">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h1>FALE CONOSCO</h1>

                    <h3>Seu contato é muito importante<br>
                        Preencha o formulário
                        abaixo com suas dúvidas, críticas ou elogios que entraremos em contato o mais breve possível.
                    </h3>
                </div>
            </div>
        </div>

        <div class="cta blue-bg clearfix">
            <div class="container clearfix">
                <div class="row-height">


                    <div id="wrapper-inner" class="col-md-8 contact-page clearfix">

                        <div class="contact-info_form clearfix cover section-padding">
                            <span class="anchor" id="contact-form"></span>

                            <h1 class="section-heading normal">Formulário de contato</h1>


                            <form action="" method="post" enctype="multipart/form-data" name="dados"
                                  onSubmit="return validaForm()" class="contact-form margint-40 clearfix">
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Nome</label>
                                        <input id="nome" data-error-message="Preencha seu nome" type="text" required=""
                                               name="nome"
                                               class="form-control input--withBorder ct-u-marginBottom10 input-focusMotive">
                                    </div>
                                    <div class="col-md-4">
                                        <label>E-mail</label>
                                        <input id="email" data-error-message="Preencha o e-mail" type="email"
                                               required="" name="email"
                                               class="form-control input--withBorder ct-u-marginBottom10 input-focusMotive">
                                    </div>
                                    <div class="col-md-4">
                                        <label>Telefone</label>
                                        <input id="tel" data-error-message="Preencha corretamente o telefone"
                                               type="text" required="" name="tel"
                                               class="form-control input--withBorder ct-u-marginBottom10 input-focusMotive"
                                               onKeyPress="mascara(this,telefone)" maxlength="15">
                                    </div>
                                </div>
                                <label>Mensagem</label>
                                <textarea id="mensagem" data-error-message="Escreva uma mensagem" rows="8" required=""
                                          name="mensagem" title="Mensagem"
                                          class="form-control input--withBorder ct-u-marginBottom20 input-focusMotive ct-u-marginBottom20"></textarea>
                                <input type="submit" value="Enviar mensagem" name="btn" id="em_submit"
                                       class="btn btn-primary2">

                            </form>


                        </div>
                    </div>

                    <div class="col-md-4 panel panel-default">
                        <div class="contact-info_form clearfix cover section-padding">

                            <h2 class="section-heading normal">Telefones</h2>
                            <h6 class=" ">
                                <i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8000<br>
                                <i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8053<br>
                                <i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8049<br><br>
                                <i class="fa fa-envelope-o" aria-hidden="true"></i> sitiojonosake@sitiojonosake.com.br
                            </h6>
<br><br>
                            <h2 class="section-heading normal">Endereço</h2>
                            <h6 class="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i> R. Norma Okasaki Inoue, 23 <br>
                                Santa Candida, Itaguaí - RJ
                                <br> CEP: 23821-590<br><br>
                            </h6>


                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- END #wrapper-inner -->

        <div class="section-info steps-section section-padding paddingt-0 row-height text-center clearfix">
            <div class="final-contato clearfix">
            </div>
        </div>
        <!-- END .steps-section -->


