<section class="title-section">
<div class="container">


<div class="row title">

<div class="col-md-9">
<h1>Eventos
<span class="line-title"></span>
</h1>
</div>

</div>

</div>
</section>


<section class="paddings">
<div class="container">
<div class="row">

<div class="col-md-8">

<?php echo $this->message(); ?>
<?php foreach ($this->eventos as $evento) { ?>
<article class="post">
    <div class="row">

   
    <div class="col-md-9">
    <h3>
    <a href="<?php echo $this->url('eventos_front', array('action' => 'detalhes', 'id' => $evento->getId())); ?>">
        <?php echo $evento->getNome(); ?>
    </a>
    </h3>
    
    <div class="row">
    <div class="col-md-12">
    <div class="post-meta">
    <span><i class="fa fa-calendar"></i> <?= $evento->getData() ?> </span>
    </div>
    </div>
    </div>

    <p><?php echo $evento->getDescricao(); ?></p>
    <a class="btn btn-primary" href="<?php echo $this->url('eventos_front', array('action' => 'detalhes', 'id' => $evento->getId())); ?>">
    Leia mais ...</a>
    </div>

    </div>
</article>
<?php } ?>

<?php echo $this->paginationControl($this->eventos, 'Sliding', 'partial/paginator', array('route' => 'eventos_front')); ?>

</div>


<div class="col-md-4 sidebars">
<aside>
    <h4>Veja Também:</h4>
    <ul class="list">
        <li><i class="fa fa-check"></i><a href="<?php echo $this->url('noticias_front') ?>">Notícias</a></li>
        <li><i class="fa fa-check"></i><a href="<?php echo $this->url('videos_front') ?>">Vídeos</a></li>
    </ul>
</aside>

<hr>

</div>

</div>
</div>

</section>

</div>