<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">

            <h2><?php echo $this->titulo; ?></h2>

            <div class="ibox-content">

                <?php echo $this->message(); ?>


                <div class="text-right">
                    <a href="<?php echo $this->url($this->routeController, array('action' => 'novo')); ?>" class="btn btn-success permissao_add"> <i class="fa fa-plus"></i> Adicionar </a>
                </div>

                <form action="" id="acao_massa" method="post">

                    <div class="table-responsive margem_table_lista">
                        <?php if (!$this->registros) { ?>       
                            <div class="alert alert-warning alert-dismissable">
                                <i class="fa fa-warning"></i> Sua busca não encontrou nenhum resultado.
                            </div>
                        <?php } ?>

                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>

                                    <th>Título</th>
                                    <th>Posição</th>
                                    <th>Ação</th>  
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->registros as $item) { ?>
                                    <tr>

                                        <td>
                                            <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>">
                                                <?php echo $item->getNome(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <?php echo $item->getPosicao(); ?>
                                        </td>

                                        <td>
                                            <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>" class="btn btn-xs btn-default permissao_remover"><span class="glyphicon glyphicon-pencil"></span></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>

                        <?php
                        echo $this->paginationControl($this->registros, 'Sliding', 'partial/paginator', array('route' => $this->routeController));
                        ?>


                    </div>
                </form>
            </div>
        </div>
    </div>

</div>