<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">

            <h2><?php echo $this->titulo; ?></h2>

            <div class="ibox-content">
                <?php echo $this->message(); ?>

                <form action="<?php echo $this->url($this->routeController); ?>">
                    <div class="row">

                        <div class="col-sm-3">
                            <div class="input-group">
                                <input name="q.nome" type="text" value="<?= $paramsQuery()->fromQuery('q_nome') ?>" placeholder="Digite um nome"
                                       class="search-query-pedidos input-sm form-control">
                            </div>
                        </div>

                        <div class="col-sm-2 m-b-xs">

                            <select name="q.cooperativa" class="input-sm form-control input-s-sm inline">
                                <option value="">Consorciada</option>
                                <?php foreach ($this->cooeprativas as $cooeprativa) { ?>
                                    <option <?php if ($paramsQuery()->fromQuery('q_cooperativa') == $cooeprativa->getId()) { ?> selected <?php } ?> value="<?php echo $cooeprativa->getId(); ?>">
                                        <?php echo $cooeprativa->getNome(); ?>
                                    </option>
                                <?php } ?>

                            </select>

                        </div>

                        <div class="col-sm-2 m-b-xs">


                            <select name="q.perfil" class="input-sm form-control input-s-sm inline">
                                <option value="">Perfil</option>
                                <?php foreach ($this->perfis as $perfil) { ?>
                                    <option <?php if ($paramsQuery()->fromQuery('q_perfil') == $perfil->getId()) { ?> selected <?php } ?> value="<?php echo $perfil->getId(); ?>">
                                        <?php echo $perfil->getNome(); ?>
                                    </option>
                                <?php } ?>

                            </select>    

                        </div>
                        
                        <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary">
                                Filtrar
                            </button>
                            <a href="<?php echo $this->url($this->routeController); ?>" class="btn btn-sm btn-prima"> <i
                                    class="fa fa-eraser"></i> Limpar</a>

                        </span>
                    </div>
                </form>

                <div class="text-right permissao_add">
                    <a href="<?php echo $this->url($this->routeController, array('action' => 'novo')); ?>" class="btn btn-success"> <i class="fa fa-plus"></i> Adicionar </a>
                </div>

                <form action="" id="acao_massa" method="post">

                    <div class="table-responsive margem_table_lista">
                        <?php if (!$this->registros) { ?>       
                            <div class="alert alert-warning alert-dismissable">
                                <i class="fa fa-warning"></i> Sua busca não encontrou nenhum resultado.
                            </div>
                        <?php } ?>

                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#ID</th>
                                    <th>Nome</th>
                                    <th>e-mail</th>
                                    <th>Cooperativa</th>
                                    <th>Perfil</th>
                                    <th>Ação</th>  
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->registros as $item) { ?>
                                    
                                    <tr>
                                        <td>
                                            <?php echo $item->getId(); ?>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>">
                                                <?php echo $item->getNome(); ?>
                                            </a>
                                        </td>

                                        <td>
                                            <?php echo $item->getEmail(); ?>
                                        </td>


                                        <td>
                                            <?php
                                               $coop = $item->getCooperativa();
                                                if ($coop) {
                                                    try {
                                                        echo $coop->getNome();
                                                    } catch (Exception $exc) {
//                                                        echo $exc->getTraceAsString();
                                                    }

                                                    
                                                }
                                            ?>
                                        </td>

                                       

                                        <td>
                                            <?php echo $item->getDataCadastro(); ?>
                                        </td>

                                        <td>
                                            <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>" class="btn btn-xs btn-default permissao_remover"><span class="glyphicon glyphicon-pencil"></span></a>
                                            <a href="<?php echo $this->url($this->routeController, array('action' => 'remover', 'id' => $item->getId())); ?>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>

                        <?php
                        echo $this->paginationControl($this->registros, 'Sliding', 'partial/paginator', array('route' => $this->routeController));
                        ?>


                    </div>
                </form>
            </div>
        </div>
    </div>

</div>