<section class="title-section">
<div class="container">

<div class="row title">

<div class="col-md-9">
<h1>Agenda
</h1>
</div>

</div>

</div>
</section>

<style>
    .table_list tr th{
        font-size: 14px;
    }
    .table_list tr td{
        font-size: 14px;
    }
</style>

<section class="paddings">
    <div class="container">

        <?php echo $this->partial('menu', array('menu' => $this->menu, 'categorias' => $this->categorias)); ?>

        <div class="col-xs-12 col-sm-12 col-md-10">

            <div class="conteudo-institucional">

                <form action="<?php echo $this->url($this->routeController, array('action' => 'agenda')); ?>">
                    <div style="padding-bottom: 20px;">
                        
<!--                        <div class="col-sm-3 m-b-xs">
                            <select name="at.nucleo" class="input-sm form-control input-s-sm inline">
                                <option value="">Filtrar por Núcleo</option>
                                <?php foreach ($this->nucleos as $item) { ?>
                                    <?php
                                    $nucleo = $item->getNucleo();
                                    ?>
                                    <option <?php if ($paramsQuery()->fromQuery('at_nucleo') == $nucleo->getId()) { ?> selected <?php } ?> value="<?php echo $nucleo->getId(); ?>">
                                        <?php //echo $nucleo->getNome(); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>-->

                        <?php
                        
                            $meses = array(
                                '01' => 'Janeiro',
                                '02' => 'Fevereiro',
                                '03' => 'Março',
                                '04' => 'Abril',
                                '05' => 'Maio',
                                '06' => 'Junho',
                                '07' => 'Julho',
                                '08' => 'Agosto',
                                '09' => 'Setembro',
                                '10' => 'Outubro',
                                '11' => 'Novembro',
                                '12' => 'Dezembro',
                            );
                        
                        ?>
                        
                        <div class="col-sm-3 m-b-xs">
                            <select name="mes"  class="input-sm form-control input-s-sm inline">
                                <option value="">Filtrar por Mês</option>
                                <?php foreach ($meses as $key => $mes) { ?>
                                    <option <?php if ($paramsQuery()->fromQuery('mes') == $key) { ?> selected <?php } ?> value="<?php echo $key; ?>">
                                        <?php echo $mes ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>


                        <div class="col-sm-3 m-b-xs">
                            <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary">
                                    Filtrar
                                </button>
                                <a href="<?php echo $this->url($this->routeController, array('action' => 'agenda')); ?>" class="btn btn-sm btn-prima"> <i
                                        class="fa fa-eraser"></i> Limpar</a>

                            </span>
                        </div>

                    </div>
                </form>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <br>
                    <?php echo $this->message(); ?>

                    <div class="table-responsive">

                        <table class="table table-striped table_list"> 
                            <thead> 
                                <tr> 
                                    <th>Evento</th> 
                                    <th>Data</th>
                                    <th></th> 
                                </tr> 
                            </thead> 
                            <tbody> 
                                <?php foreach ($this->eventos as $item) { ?>
                                    <tr> 
                                        <td>
                                            <a href="<?php echo $this->url('usuarios_front', array('action' => 'detalhes-agenda', 'id' => $item->getId())); ?>">
                                                <?php echo $item->getNome(); ?>
                                            </a>
                                        </td>
                                      
                                        <td>
                                            <?php echo $item->getData(); ?>
                                        </td> 

                                        <td>
                                            <a href="<?php echo $this->url('usuarios_front', array('action' => 'detalhes-agenda', 'id' => $item->getId())); ?>">
                                                <span class="label label-info"> + Detalhes </span>
                                            </a>
                                        </td> 
                                    </tr> 
                                <?php } ?>

                            </tbody> 
                        </table>


                    </div>				
                </div>

            </div>
        </div>

    </div>
</section>