<section class="title-section">
<div class="container">

<div class="row title">

<div class="col-md-9">
<h1>Documentos
</h1>
</div>

</div>

</div>
</section>

<style>
    .table_list tr th{
        font-size: 14px;
    }
    .table_list tr td{
        font-size: 14px;
    }
</style>

<section class="paddings">
    
    <div class="container">

        <?php echo $this->partial('menu', array('menu' => $this->menu, 'categorias' => $this->categorias)); ?>

        <div class="row">

            <div class="conteudo-institucional">

                <form action="<?php echo $this->url($this->routeController, array('action' => 'documentos')); ?>">
                    <div style="padding-bottom: 20px;">

                        <div class="col-sm-3">
                            <div class="input-group">
                                <input name="q.nome" type="text" value="<?= $paramsQuery()->fromQuery('q_nome') ?>" placeholder="Buscar por nome do arquivo"
                                       class="search-query-pedidos input-sm form-control">
                            </div>
                        </div>

                        <div class="col-sm-3 m-b-xs">
                            <select name="q.categoria"  class="input-sm form-control input-s-sm inline">
                                <option value="">Filtrar por Categoria</option>
                                <?php foreach ($this->categorias as $categoria) { ?>
                                    <option <?php if ($paramsQuery()->fromQuery('q_categoria') == $categoria->getId()) { ?> selected <?php } ?> value="<?php echo $categoria->getId(); ?>">
                                        <?php echo $categoria->getNome(); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>

<!--                        <div class="col-sm-3 m-b-xs">
                            <select name="at.nucleo" class="input-sm form-control input-s-sm inline">
                                <option value="">Filtrar por Núcleo</option>
                                <?php foreach ($this->nucleos as $item) { ?>
                                    <?php
                                    $nucleo = $item->getNucleo();
                                    ?>
                                    <option <?php if ($paramsQuery()->fromQuery('at_nucleo') == $nucleo->getId()) { ?> selected <?php } ?> value="<?php echo $nucleo->getId(); ?>">
                                        <?php //echo $nucleo->getNome(); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>-->


                        <div class="col-sm-3 m-b-xs">
                            <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary">
                                    Filtrar
                                </button>
                                <a href="<?php echo $this->url($this->routeController, array('action' => 'documentos')); ?>" class="btn btn-sm btn-prima"> <i
                                        class="fa fa-eraser"></i> Limpar</a>

                            </span>
                        </div>

                    </div>
                </form>

                <div class=" col-md-8">
                    <br>
                    <?php echo $this->message(); ?>

                    <div class="table-responsive">

                        <table class="table table-striped table_list"> 
                            <thead> 
                                <tr> 
                                    <th>Nome do arquivo</th> 
                                    <th>Categoria</th> 
                                    <th>Data</th>
                                    <th></th> 
                                </tr> 
                            </thead> 
                            <tbody> 
                                <?php foreach ($this->documentos as $item) { ?>
                                    <tr> 
                                        <td>
                                            <a style="font-size: 14px" href="<?php echo $this->url('usuarios_front', array('action' => 'detalhes-documento', 'id' => $item->getId())); ?>">
                                                <?php echo $item->getNome(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <?php echo $item->getCategoria()->getNome(); ?>
                                        </td>
                                        <td>
                                            <?php echo $item->getDataCriacao(); ?>
                                        </td> 

                                        <td>
                                            <a  href="<?php echo $this->url('usuarios_front', array('action' => 'detalhes-documento', 'id' => $item->getId())); ?>">
                                                <span class="label label-info"> + Detalhes </span>
                                            </a>
                                        </td> 
                                    </tr> 
                                <?php } ?>

                            </tbody> 
                        </table>


                    </div>				
                </div>

            </div>
        </div>
        <div style="margin-left: 215px">
            <?php 
                if($this->documentos){
                    echo $this->paginationControl($this->documentos, 'Sliding', 'partial/paginator', array('route' => $this->routeController, 'action' => 'documentos')); 
                }
                
            ?> 
        </div>   
    </div>
</section>