       <div class="header-box-inner cover-fix" style="background-image: url('http://www.jonosake.com.br/images/fundo_slide_2.jpg');">
            <div class="circle-line circle-line-bottom circle-line2"></div>
            <div class="container">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h1>O DIA NO SÍTIO</h1>

                    <h3>PROGRAMAÇÃO REGULAR.</h3>
                </div>
            </div>
        </div>

        <div class="cta blue-bg clearfix">
            <div class="container clearfix">
                <div class="row-height">

                    <div class="col-md-6">
                        <div class="ct-infoBox ct-infoBox--vertical ct-u-marginBottom70">
                            <div class="ct-infoBox-description">

                                <p style="text-align: justify">
                                    Para quem está procurando diversão ou para quem está procurando descanso!<br>Isso
                                    mesmo, no Sítio Jonosake temos o equilíbrio perfeito para quem quer muita diversão
                                    ou para quem prefere curtir uma tarde descansando em nosso jardim japonês.
                                    <br><br>
                                    Nosso dia é repleto de boa comida e bebida, a começar pelo café da manhã... almoço
                                    com buffet com churrasco e variado, bebidas liberadas, além de petiscos e aquele
                                    cafezinho da tarde com gostinho de sítio.
                                    <ul class="list-unstyled ct-list--WithIcons ct-u-marginBottom30 ct-u-marginTop30">
                                        <li><h4>60.000m²</h4></li>
                                        <li><h4>6 piscinas</h4></li>
                                        <li><h4>Jardim Japonês</h4></li>
                                        <li><h4>Tirolesa</h4></li>
                                        <li><h4>Arvorismo</h4></li>
                                        <li><h4>Salões cobertos</h4></li>
                                        <li><h4>Circo</h4></li>
                                        <li><h4>Parquinho</h4></li>
                                        <li><h4>Berçário</h4></li>
                                        <li><h4>Quiosques</h4></li>
                                        <li><h4>Futebol de areia</h4></li>

                                    </ul>
                                    Ambulatório, equipe médica, salas de repouso também farão você ter mais
                                    tranquilidade.

                                </p>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="panel-group">
                            <div class="panel panel-default">
                                <div id="collapseOne" role="tabpanel" aria-labelledby="headingOne"
                                     class="panel-collapse collapse in">
                                    <div class="panel-body">
                                        <h4 class="text-center">PROGRAMAÇÃO</h4>
                                        <div class="ct-js-gallery ct-gallery ct-listing">

                                            <div class="ct-gallery-item alimentacao">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">08:30 às 10:00</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Café da manhã</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">09:45 às 11:00</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Atividades interativas com equipe de recreadores Jonosake</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item alimentacao">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">11:00 às 15:00</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Bebidas liberadas (Cerveja, refrigerante, vinho, suco e água)</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item alimentacao">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">11:15 às 12:15</div>
                                                    <div class="ct-u-displayTableCell"><span
                                                            class="ct-price">Petiscos</span></div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">11:30 às 16:30</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Música ao Vivo</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item alimentacao">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">11:40 às 12:45</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Caldo verde</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item alimentacao">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">13:30 às 15:00</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Almoço com sobremesa, chá e café.</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">15:15</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Apresentações folclóricas e atividades participativas.</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">15:40</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Tema do mês</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">16:30</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Homenagem aos aniversariantes da semana.</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="ct-gallery-item atividades">
                                                <div class="ct-u-displayTableVertical">
                                                    <div class="ct-u-displayTableCell">16:45</div>
                                                    <div class="ct-u-displayTableCell"><span class="ct-price">Despedida com canjica doce</span>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>

                                        <div>
                                            <p>
                                                <small style="line-height: 18px; margin-top: 10px;">
                                                    * O Sítio Jonosake se reserva ao direito de alterar o cardápio e a
                                                    programação sempre que necessário.
                                                    <br>* O consumo de bebidas fora do horário (11:00h às 15:00h) não
                                                    está incluso no pacote.
                                                    <br>* O Sítio Jonosake somente funcionará mediante o fechamento com
                                                    o mínimo de setecentos clientes.
                                                </small>
                                            </p>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <!-- END CTA -->

            <div class="section-info steps-section section-padding paddingt-0 row-height text-center clearfix">

                <!-- <div class="second-row clearfix">

                    
                    <script src="https://snapwidget.com/js/snapwidget.js"></script>
                    <iframe src="https://snapwidget.com/embed/383636" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>

                </div> -->


                <div class="first-row clearfix">
                    <div class="container">
                        <div class="row-height">
                            <div class="steps-info col-height col-md-12">
                                <!-- <h1>O SEU DIA É MAIS FELIZ AQUI!</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
