<?php
$formLogin = $this->FormLogin();
$dadosUser = $this->dadosUserFront();
$em = $this->getEm();

$institucionais = $em->getRepository("Institucional\Entity\Instituicao")->listagemHome();
?>

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Basic -->
        <meta charset="utf-8">
        <title>FECOAGRO Leite Minas</title> 
        <meta name="keywords" content="FECOAGRO" />
        <meta name="description" content="RFECOAGRO">

        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <!-- Theme CSS -->
        <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $this->basePath(); ?>/front/css/style.css"/>
        <!-- Responsive CSS -->
        <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $this->basePath(); ?>/front/css/theme-responsive.css"/>
        <!-- Skins Theme -->
        <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $this->basePath(); ?>/front/css/skins/green/green.css"/>

        <!-- Head Libs -->
        <script src="<?php echo $this->basePath(); ?>/front/js/modernizr.js"></script>

        <!-- Favicons -->
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/front/img/icons/favicon.ico">
        <link rel="apple-touch-icon" href="<?php echo $this->basePath(); ?>/front/img/icons/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->basePath(); ?>/front/img/icons/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->basePath(); ?>/front/img/icons/apple-touch-icon-114x114.png">   
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/jquery.js"></script> 
        <!-- styles for IE -->
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/front/css/ie/ie.css" type="text/css" media="screen" />            
        <![endif]-->


        <!--[if lte IE 8]>
            <script src="<?php echo $this->basePath(); ?>/front/js/responsive/html5shiv.js"></script>
            <script src="<?php echo $this->basePath(); ?>/front/js/responsive/respond.js"></script>
        <![endif]-->
    </head>
    <body> 

 
    <!-- layout-->
    <div id="layout" class="layout-wide">
        
        <section class="info-head">  
            <div class="container">
                <ul>  
                    <li><i class="fa fa-phone"></i> (34) 3818-3777</li>
                    <li><i class="fa fa-envelope"></i> gabriella.fecoagro@gmail.com </li>                    
                </ul>
                <div class="pull-right">
                    <a>Intranet</a>
                </div>
            </div>
            
        </section>
        <!-- Info Head -->

        <!-- Header-->
        <header>           
            <!-- Container-->
            <div class="container">
                <!-- Row-->
                <div class="row">
                    <!-- Logo-->
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="/" title="Home">                            
                                <img src="<?php echo $this->basePath(); ?>/front/img/logo.png" alt="Logo" class="logo_img">
                            </a>
                        </div>
                    </div>
                    <!-- End Logo-->
                                                      
                    <!-- Nav-->
                    <nav class="col-md-9">
                        <!-- Menu-->
                        <ul id="menu" class="sf-menu">
                            <li>
                                <a href="/">HOME </a>
                            </li>
                            <li><a href="">INSTITUCIONAL<i class="fa fa-angle-down"></i></a>
                                <ul> 
                                    <?php foreach($institucionais as $pagina) {?>                        
                                        <li><a href="<?php echo $this->url('institucional_front', array('action' => 'pagina', 'id' => $pagina->getId())); ?>"><?php echo $pagina->getNome() ?></a></li>
                                    <?php }?>
                                </ul>
                            </li>
                           
                            <li><a href="">COOPERATIVAS<i class="fa fa-angle-down"></i></a>
                                <ul> 
                                    <li><a href="<?php echo $this->url('consorciadas_front') ?>">Associadas</a></li>
                                    <li><a href="<?php echo $this->url('consorciadas_front', array('action' => 'produtos')) ?>">Produtos</a></li>
                                </ul>
                            </li>

                            <li>
                                <a href="<?php echo $this->url('eventos_front', array('action' => 'index')) ?>">EVENTOS </a>
                            </li>   
                            <li>
                                <a href="<?php echo $this->url('noticias_front', array('action' => 'index')) ?>">NOTÍCIAS </a>
                            </li>
                                        
                            <li>
                                <a href="<?php echo $this->url('videos_front', array('action' => 'index')) ?>">VÍDEOS</a>
                            </li>

                            <li><a href="<?php echo $this->url('contato') ?>">CONTATO</a></li>
                        </ul>
                        <!-- End Menu-->
                    </nav>
                    <!-- End Nav-->
                </div>
                <!-- End Row-->
            </div>
            <!-- End Container-->
        </header>
        <!-- End Header-->

        <?php echo $this->content ?>

        <!-- footer Center-->
        <footer class="footer-center">
            <div class="container">
                <!-- Info Top - Footer Center-->
                <div class="row">   
                   <div class="col-md-4 item-center">
                        <span class="arrow_footer"></span>
                        <i class="fa fa-phone"></i>
                        <h4>(34) 3818-3777</h4>                        
                   </div>
                   <div class="col-md-4 item-center">
                       <span class="arrow_footer"></span>
                        <i class="fa fa-envelope"></i>
                        <h4>gabriella.fecoagro@gmail.com</h4>                        
                   </div>
                   <div class="col-md-4 item-center">
                        <span class="arrow_footer"></span>
                        <i class="fa fa-comment"></i>
                        <h4>
                        <a href="<?php echo $this->url('contato') ?>">
                            Fale conosco
                        </a>
                        </h4> 
                   </div>
                </div>   
                <!-- End Info Top - Footer Center-->


            </div>
        </footer>      
        <!-- End footer Center-->

        <!-- footer bottom-->
        <footer class="footer-bottom">
            <div class="container">
               <div class="row">   
                                                                  
                    <!-- Nav-->
                    <div class="col-md-8">
                        <div class="logo-footer">
                            <h2>FECOAGRO <small>Leite Minas</small></h2>
                        </div>
                        <!-- Menu-->

                        <!-- coopring-->
                       <div class="row coopring">
                           <div class="col-md-8">
                               <p> Todos os direitos reservados</p>
                           </div>
                       </div>    
                       <!-- End coopring-->  
                    </div>
                    <!-- End Nav-->

                    <!-- Social-->
                    <div class="col-md-4">
                        <!-- Menu-->
                        <ul class="social">
                            <li data-toggle="tooltip" title data-original-title="Facebook">
                                <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            </li> 
                            
                            <li data-toggle="tooltip" title data-original-title="Youtube">
                                <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            </li>                     
                        </ul>
                        <!-- End Menu-->
                    </div>
                    <!-- End Social-->

               </div> 
                    
            </div>
        </footer>      
        <!-- End footer bottom-->
    </div>
    <!-- End layout-->

    <!-- ======================= JQuery libs =========================== -->
    <!-- jQuery local-->
    
    <!--Nav-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/nav/tinynav.js"></script> 
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/nav/superfish.js"></script>  
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/nav/hoverIntent.js"></script>  
    <script src="<?php echo $this->basePath(); ?>/front/js/nav/jquery.sticky.js" type="text/javascript"></script>                                          
    <!--Totop-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/totop/jquery.ui.totop.js" ></script>  
    <!--Slide Revolution-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/rs-plugin/js/jquery.themepunch.tools.min.js" ></script>      
    <script type='text/javascript' src='<?php echo $this->basePath(); ?>/front/js/rs-plugin/js/jquery.themepunch.revolution.min.js'></script>  
    <!--Ligbox--> 
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/fancybox/jquery.fancybox.js"></script> 
    <!-- carousel.js-->
    <script src="<?php echo $this->basePath(); ?>/front/js/carousel/carousel.js"></script>  
    <!-- Twitter Feed-->
    <script src="<?php echo $this->basePath(); ?>/front/js/twitter/jquery.tweet.js"></script> 
    <!-- flickr Feed-->
    <script src="<?php echo $this->basePath(); ?>/front/js/flickr/jflickrfeed.min.js"></script>  
    <!--Scroll-->   
    <script src="<?php echo $this->basePath(); ?>/front/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Maps -->
    <script src="<?php echo $this->basePath(); ?>/front/js/maps/gmap3.js"></script>
    <!-- Filter -->
    <script src="<?php echo $this->basePath(); ?>/front/js/filters/jquery.isotope.js" type="text/javascript"></script>
    <!-- Parallax-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/parallax/jquery.inview.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/parallax/nbw-parallax.js"></script>  

    <!-- Bootstrap.js-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/bootstrap/bootstrap.js"></script>
    <!--MAIN FUNCTIONS-->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/front/js/main.js"></script>
    <!-- ======================= End JQuery libs =========================== -->

    <!--Slider Function-->
    <script type="text/javascript">
        var revapi;
        jQuery(document).ready(function() {
           revapi = jQuery('.tp-banner').revolution(
            {
                delay:9000,
                startwidth:1170,
                startheight:580,
                spinner:"spinner4",
                hideThumbs:10,
                fullWidth:"on",
                navigationType:"none",
                navigationArrows:"solo",
                navigationStyle:"preview4",
                forceFullWidth:"on"
            });
        }); 
    </script>
    <!--End Slider Function-->
        
    </body>
</html>