<section class="title-section">
<div class="container">

<div class="row title">

<div class="col-md-9">
<h1>Vídeos
</h1>
</div>

</div>

</div>
</section>


<section class="paddings">
<div class="container">
<div class="row">

<div class="col-md-8">

<article class="post">
<h2><a href="#"><?php echo $video->getNome(); ?></a></h2>

<div class="clearfix"></div>

<div class="post-meta">
<span><i class="fa fa-calendar"></i> <?php echo $video->getDataCriacao(); ?> </span>
</div>

<div class="info-post">
    <?php echo $video->getTexto(); ?>
</div>

</article>

</div>

<div class="col-md-4 sidebars">

<aside>
    <h4>Veja Também</h4>
    <ul class="list">
        <li><i class="fa fa-check"></i><a href="<?php echo $this->url('noticias_front') ?>">Notícias</a></li>
        <li><i class="fa fa-check"></i><a href="<?php echo $this->url('eventos_front') ?>">Eventos</a></li>
    </ul>
</aside>

<hr>

</div>

</div>
</div>

</section>

</div>