<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->titulo ?></h2>
    </div>
    <div class="col-lg-">
        <div class="ibox float-e-">

            <div class="ibox-">
                <div class="panel- col-lg-">
                    
                    <?php if($this->erro) {?>
                        <div id="alert-message">
                            <div class="alert alert-danger alert-block fade in">
                                <button type="button" class="close" data-dismiss="alert">×</button>Verifique os erros.
                            </div>
                        </div>
                    <?php } ?>
                    
                    <?php
                        
                        $this->form->prepare();
                        if($this->registro){
                            $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'editar', 'id' => $this->registro->getId())));
                        }else{
                            $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'novo')));
                        }
    
                    ?>

                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    
                    echo $this->formHidden($this->form->get('id'));
                    echo $this->formElement($this->form->get('csrf'));
                    ?>
                    
                    <div class="panel blank-panel" >

                       

                        <div class="panel-body" style="margin-left: 15px">
                            <div class="tab-content">

                                <div class="tab-pane active" id="tab-1">
  
                                    <div class="form-group">
                                        <label>Título: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('nome'));
                                        echo $this->formElementErrors()->render($this->form->get('nome'));
                                        ?>
                                    </div>
                                        <div class="form-group">
                                        <label>Descrição: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('descricao'));
                                        echo $this->formElementErrors()->render($this->form->get('descricao'));
                                        ?>
                                    </div>   

                                    <div class="form-group">
                                        <label>Publicar no site? </label>
                                        <?php
                                        echo $this->formCheckBox($this->form->get('publico'));
                                        echo $this->formElementErrors()->render($this->form->get('publico'));
                                        ?>
                                    </div>
           
                                    <div class="form-group">
                                        <label>Data do Evento: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('data'));
                                        echo $this->formElementErrors()->render($this->form->get('data'));
                                        ?>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Texto: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('texto'));
                                        echo $this->formElementErrors()->render($this->form->get('texto'));
                                        ?>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Origem: <span class="required">*</span></label>
                                        <div class="checks_manytomany">
                                            <?php
                                                echo $this->formMultiCheckbox($this->form->get('nucleo'));
                                                echo $this->formElementErrors()->render($this->form->get('nucleo'));
                                            ?>
                                            </div>
                                    </div>
                                    
         
                                    <div class="form-group">
                                        <label>Destino: <span class="required">*</span></label>
                                        <div class="checks_manytomany">
                                            <?php
                                                echo $this->formMultiCheckbox($this->form->get('perfil'));
                                                echo $this->formElementErrors()->render($this->form->get('perfil'));
                                            ?>
                                            </div>
                                    </div>
                                    
                                    <div class="form-group permissao_add permissao_editar">
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                                name="salvar" value="1" style="margin-left: 15px">
                                            <strong>Salvar</strong>
                                        </button>
                                    </div>

                                  
                                </div>

                            </div>

                        </div>
                    </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
    
    
    <?php
if($this->registro){?>
    <script>
        $(document).ready(function(){
            <?php foreach ($this->registro->getNucleoAgenda() as $nucleo) {?>
                    $("#nucleo_<?php echo $nucleo->getNucleo()->getId(); ?>").attr('checked', true);
            <?php }?>
            <?php foreach ($this->registro->getPerfilAgenda() as $perfil) {?>
                    $("#perfil_<?php echo $perfil->getPerfil()->getId(); ?>").attr('checked', true);
            <?php }?>    
        });
    </script>
    
<?php }