

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">

            <div class="ibox-content">

                <div class="panel-body col-lg-6">

                    Tem certeza?
                    <form action="<?php echo $this->url($this->routeController, array('action' => 'remover', 'id' => $registro->getId())); ?>" method="post" role="form">
                          
                          <div class="form-group">

                            <a href="<?php echo $this->url($this->routeController); ?>" class="btn btn-sm pull-left m-t-n-xs" type="submit"
                               name="salvar" value="1" style="margin-left: 15px">
                               <strong>Não, voltar</strong></a>

                            <button class="btn btn-sm btn-primary pull-left m-t-n-xs" type="submit"
                                    name="salvar" value="1" style="margin-left: 15px">
                                <strong>Sim, tenho certeza</strong></button>

                        </div>

                    </form>

                </div>

            </div>
        </div>
    </div>
</div>

