<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->titulo ?></h2>
    </div>
    <div class="col-lg-">
        <div class="ibox float-e-">

            <div class="ibox-">
                <div class="panel- col-lg-">

                    <?php if ($this->erro) { ?>
                        <div id="alert-message">
                            <div class="alert alert-danger alert-block fade in">
                                <button type="button" class="close" data-dismiss="alert">×</button>Verifique os erros.
                            </div>
                        </div>
                    <?php } ?>

                    <?php
                    $this->form->prepare();
                    if ($this->registro) {
                        $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'editar', 'id' => $this->registro->getId())));
                    } else {
                        $this->form->setAttribute('action', $this->url($this->routeController, array('action' => 'novo')));
                    }
                    ?>

                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    echo $this->formHidden($this->form->get('id'));
                    echo $this->formElement($this->form->get('csrf'));
                    ?>

                    <div class="panel blank-panel" >


                        <div class="panel-body" style="margin-left: 15px">
                            <div class="tab-content">

                                <div class="tab-pane active" id="tab-1">




                                    <div class="form-group">
                                        <label>Título: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('nome'));
                                        echo $this->formElementErrors()->render($this->form->get('nome'));
                                        ?>
                                    </div>



                                    <div class="form-group">
                                        <label>Descrição: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('descricao'));
                                        echo $this->formElementErrors()->render($this->form->get('descricao'));
                                        ?>
                                    </div>   


                                    <div class="form-group">
                                        <label>Texto: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('texto'));
                                        echo $this->formElementErrors()->render($this->form->get('texto'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Imagem: </label>
                                        <?php
                                        echo $this->formInput($this->form->get('imagem'));
                                        echo $this->formElementErrors()->render($this->form->get('imagem'));
                                        ?>
                                    </div>

                                    <div class="form-group permissao_add permissao_editar">
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                                name="salvar" value="1" style="margin-left: 15px">
                                            <strong>Salvar</strong>
                                        </button>
                                    </div>


                                </div>

                            </div>

                        </div>
                    </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

    <script>
        var editor = CKEDITOR.replace('editor1', {
            language: 'pt-br',
            height: 500,
            toolbarCanCollapse: true,
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html?type=Images',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html?type=Flash',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });
        CKFinder.setupCKEditor(editor, '../');
    </script>