<?php $dadosUser = $this->DadosUser();?>
<style type="text/css">
    <?php 
        echo (new \Keep\Helper\PermissoesView())->permitido($dadosUser, $this->layout()->current_route);
    ?>
</style>

<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->titulo ?></h2>
    </div>
    <div class="col-lg-">
        <div class="ibox float-e-">

            <div class="ibox-">
                <div class="panel- col-lg-">
                    <?php echo $this->message(); ?>
                    <?php if($this->erro) {?>
                        <div id="alert-message">
                            <div class="alert alert-danger alert-block fade in">
                                <button type="button" class="close" data-dismiss="alert">×</button>Verifique os erros.
                            </div>
                        </div>
                    <?php } ?>
                    
                    <?php
                        
                        $this->form->prepare();
                        $this->form->setAttribute('action', $this->url('admin', array('action' => 'senha')));
    
                    ?>

                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    
                 
                    echo $this->formElement($this->form->get('csrf'));
                    ?>
                    
                    <div class="panel blank-panel" >

                        <div class="panel-heading">
                            <div class="panel-options">
                                <ul class="nav nav-tabs">

                                    <li class="active"><a href="#tab-1" data-toggle="tab"> Info. Básicas </a></li>
                                    
                                </ul>
                            </div>
                        </div>

                        <div class="panel-body" style="margin-left: 15px">
                            <div class="tab-content">

                                <div class="tab-pane active" id="tab-1">
                                    
                                    
                                   
                                    <div class="form-group">
                                        <label>Senha: </label>
                                        
                                        <?php
                                        echo $this->formInput($this->form->get('senha'));
                                        echo $this->formElementErrors()->render($this->form->get('senha'));
                                        ?>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Confirme a senha: </label>
                                        
                                        <?php
                                        echo $this->formInput($this->form->get('confirme_senha'));
                                        echo $this->formElementErrors()->render($this->form->get('confirme_senha'));
                                        ?>
                                    </div>
                                    
                                     <div class="form-group ">
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                                name="salvar" value="1" style="margin-left: 15px">
                                            <strong>Salvar</strong>
                                        </button>
                                    </div>

                                  
                                </div>

                            </div>

                        </div>
                    </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
    