        <div id="main" class="clearfix">
            <div class="carousel fade-carousel slide slider-home" data-ride="carousel" data-interval="4000"
                id="bs-carousel">

                <!-- Indicators -->
                <ol class="carousel-indicators">

                    <?php 
                    $count = 0;
                    foreach($this->banners as $banner) {?>
                        <li data-target="#bs-carousel" data-slide-to="<?php echo $count ?>" class="<?php if($count == 1) {?>  active <?php }?>"></li>
                    <?php $count++; } ?>
                </ol>

                <div class="carousel-inner">

                    <?php 
                    $count = 0;
                    foreach($this->banners as $banner) {?>
                        <div class="item slides <?php if($count == 1) {?>  active <?php }?> ">
                            <div class="slide-3" style="background-image: url(uploads/banners/<?php echo $banner->getArquivo() ?>?==12); ">
                                <!-- <div class="clown absolute animated fadeInUp scroll-time2">
                                    <img src="< ?php echo $this->basePath(); ?>/front/images/bruno_dancando.png" alt="">
                                </div> -->

                                <div class="container clearfix hero-container">
                                    <div class="hero col-md-12 col-sm-12 col-xs-12">
                                        <!-- <div class="hgroup">
                                            <h1 class="animated fadeInDown scroll-time5">
                                                < ?php echo $banner->getNome();  ?>
                                            </h1>
                                        </div> -->

                             <?php
                                
                                $link = $banner->getLink();
                                if ($link) {?>
                                    <div class="btn-box animated fadeIn scroll-time9 clearfix">
                                        <a href="<?php echo $banner->getLink(); ?>" class="transparent-btn happykiddo-btn">
                                        <?php echo $banner->getNome();  ?>
                                        </a>
                                    </div>
                            <?php } ?>
                                        
                                    </div>
                                </div>

                                

                            </div>                        
                        </div>
                    <?php $count++; } ?>


                </div>
            </div>


            <div class="cta blue-bg clearfix">
                <div class="container clearfix">
                    <div class="row-height">
                    </div>
                </div>
            </div>



            <div class="row blue-bg">
                <div class="container">
                    <div class="services clearfix">





                                <?php foreach($this->noticias as $noticia) {?>
                                    <!-- Item testimonial --> 















                        <div class="col-service col-md-6 col-sm-6 col-xs-12">
                            <div class="row row-height blue-bg2">
                                <div class="service-img cover-fix col-height col-md-6 col-sm-6 col-xs-12 clearfix" style="background-image: url('gestao/bloco-home/imagem?image=noticias/<?php echo $noticia->getImagem(); ?>&x=380&y=470');">
                                    <div class="mask">
                                        <a href="http://www.jonosake.com.br/nova-tabela">
                                            <div class="mask-btn">
                                              <i class="fa fa-eye" aria-hidden="true"></i>
                                              <span>Saiba mais</span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="service-info col-height col-md-6 col-sm-6 col-xs-12 clearfix">
                                    <h2><span><?php echo $noticia->getNome() ?></h2>
                                    <h4><?php echo $noticia->getDescricao() ?><br><br></h4>
                                    <a href="http://www.jonosake.com.br/nova-tabela" class="transparent-btn happykiddo-btn">SAIBA MAIS</a>
                                </div>
                            </div><br><br><br><br>
                        </div>
 
                        
<?php }?>



</div>
    </div>



        <!-- box-action -->
        <!-- <section class="box-action">
            <form method="post" action="< ?php echo $this->url('noticias_front', array('action' => 'news-letter')) ?>">
            <div class="container">
                <div class="title">
                    <p class="lead">Receba nossas noticias por e-mail!</p>
                </div>
                <div class="button">
                    <input type="text" required name="nome" placeholder="Nome">
                    <input type="email" required name="email" placeholder="E-mail">
                    <input type="submit" class="enviar" name="Enviar" value="Enviar">

                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                </div>
            </div>
            </form>

        </section> -->
        <!-- End box-action-->


        






            <div class="section-info steps-section section-padding paddingt-0 row-height text-center clearfix">

                <!-- <div class="second-row clearfix">

                    
                    <script src="https://snapwidget.com/js/snapwidget.js"></script>
                    <iframe src="https://snapwidget.com/embed/383636" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>

                </div> -->


                <div class="first-row clearfix">
                    <div class="container">
                        <div class="row-height">
                            <div class="steps-info col-height col-md-12">
                                <!-- <h1>O SEU DIA É MAIS FELIZ AQUI!</h1> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>






