<?php

$env = getenv('APPLICATION_ENV') ?: 'production';

//ini_set('display_errors', 'on');
date_default_timezone_set('America/Sao_Paulo');
setlocale(LC_TIME, "pt_BR");
setlocale(LC_ALL, 'pt_BR');

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'EdpModuleLayouts',
        'DoctrineModule',
        'DoctrineORMModule',
        'Institucional',
        'Cooperativa',
        'Projeto',
        'Usuario',
        'Gestao',
        'Admin',
        'Login',
        'Site',
        'Marketing',
        
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php', $env,
        ),
    ),
);
