<!DOCTYPE html>
<html>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php
        $NAME_APPLICATION = 'CCGC';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        ?>

        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="<?php echo $this->basePath(); ?>/css/animate.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/custom.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/js/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/switchery/switchery.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/chosen/chosen.css" rel="stylesheet">

        <script src="<?php echo $this->basePath(); ?>/js/jquery-2.1.1.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/plugins/jquery-ui/jquery-ui.min.js"></script>

        <script src="<?php echo $this->basePath(); ?>/js/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    </head>

    <body>

        <div id="wrapper">
            
            <nav class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">

                        <li class="nav-header">
                            <div class="dropdown profile-element">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                    <span class="clear"> <span class="block m-t-xs">
                                            <strong class="font-bold">Nome</strong>
                                        </span> </span>
                                </a>
                                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                    <li><a href="">Sair</a></li>
                                </ul>
                            </div>
                            <div class="logo-element">
                                ES
                            </div>
                        </li>

                        <li id="menu_pedidos">
                            <a href="#"><i class="fa fa-barcode"></i> <span class="nav-label">Pedidos</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="">Lista de Pedidos</a></li>
                            </ul>
                        </li>


                        <li id="menu_produtos">
                            <a href="#"><i class="fa fa-cubes"></i> <span class="nav-label">Produtos</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">

                                <li><a href="">Cardápio</a></li>
                                <li><a href="">Divisões do Cardápio</a></li>

                            </ul>
                        </li>


                        <li id="menu_restaurantes">
                            <a href="#"><i class="fa fa-cutlery"></i> <span class="nav-label">Gestão</span><span
                                    class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="">Restaurantes</a></li>
                                <li><a href="">Categorias</a></li>
                                <li><a href="">Formas de Pagamento</a></li>
                                <li><a href="">Cidades</a></li>
                            </ul>
                        </li>

                        <li id="menu_usuarios">
                            <a href="#"><i class="fa fa-users"></i> <span class="nav-label">Cadastro de Usuários</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="">Usuários</a></li>
                            </ul>
                        </li>



                    </ul>

                </div>
            </nav>
                
            <div id="page-wrapper" class="gray-bg">

                <!-- Tool bar rop -->


                <div class="row border-bottom">
                    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                        <div class="navbar-header">
                            <span minimaliza-sidebar></span>
                            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i
                                    class="fa fa-bars"></i> </a>
                        </div>
                        <ul class="nav navbar-top-links navbar-right">


                            <li>
                                <a href="">
                                    <i class="fa fa-cogs"></i>Configurações
                                </a>
                            </li>


                            <li>
                                <a href="">
                                    <i class="fa fa-gear"></i> Alterar Senha
                                </a>
                            </li>

                            <li>
                                <a href="">
                                    <i class="fa fa-sign-out"></i> Sair
                                </a>
                            </li>

                        </ul>

                    </nav>
                </div>


                <div class=" animated fadeInRight">
                    <div class="row wrapper border-bottom white-bg page-heading">
                        <div class="col-lg-12">


                            <h2>Titulo da tela</h2>

                        </div>

                        <div class="row" style="clear: both; margin: 0 14px">

                            <div style="padding: 0 0 20px 0">
                                <?php echo $this->content; ?>
                            </div>
                        </div>


                    </div>

                </div>

                <script src="<?php echo $this->basePath(); ?>/js/inspinia.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/plugins/datapicker/bootstrap-datepicker.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/plugins/pace/pace.min.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/plugins/iCheck/icheck.min.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/jquery.mask.min.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/plugins/switchery/switchery.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/jquery.word-and-character-counter.min.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/plugins/chosen/chosen.jquery.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/jquery.magnific-popup.min.js"></script>
                <script src="<?php echo $this->basePath(); ?>/js/custom.js"></script>



                </body>

                </html>