<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">

            <h2><?php echo $this->titulo; ?></h2>

            <div class="ibox-content">
                <?php echo $this->message(); ?>

                <form action="<?php echo $this->url($this->routeController); ?>">
                    <div class="row">

                        <div class="col-sm-3">
                            <div class="input-group">
                                <input name="nome" type="text" value="<?= $paramsQuery()->fromQuery('nome') ?>" placeholder="Digite um nome"
                                       class="search-query-pedidos input-sm form-control">

                            </div>
                        </div>

                        <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary">
                                Filtrar
                            </button>
                            <a href="<?php echo $this->url($this->routeController); ?>" class="btn btn-sm btn-prima"> <i
                                    class="fa fa-eraser"></i> Limpar</a>

                        </span>
                    </div>
                </form>

                <div class="text-right permissao_add">
                    <a href="<?php echo $this->url($this->routeController, array('action' => 'novo')); ?>" class="btn btn-success"> <i class="fa fa-plus"></i> Adicionar </a>
                </div>



                <div class="table-responsive margem_table_lista">
                    <?php if (!$this->registros) { ?>       
                        <div class="alert alert-warning alert-dismissable">
                            <i class="fa fa-warning"></i> Sua busca não encontrou nenhum resultado.
                        </div>
                    <?php } ?>

                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nome</th>
                                <th>Cadastro</th>
                                <th>Ação</th>  
                            </tr>
                        </thead>

                        <tbody>
                            <?php foreach ($this->registros as $item) { ?>
                                <tr>
                                    <td>
                                        <?php if (!$item->getEnviado()) { ?>
                                            <form action="<?php echo $this->url($this->routeController, array('action' => 'envio-fila-documento')); ?>" method="post">
                                                <input name="documento" type="hidden" value="<?php echo $item->getId() ?>" >
                                                <button class="btn btn-sm btn-primary m-t-n-xs" type="submit"name="salvar" value="1" style="margin-left: 15px">
                                                    <strong>Enviar para usuários</strong>
                                                </button>
                                            </form>
                                            
                                        <?php } else { ?>
                                            <span class="label label-success">Enviado</span>
                                        <?php } ?>
                                    </td>

                                    <td>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>">
                                            <?php echo $item->getNome(); ?>
                                        </a>
                                    </td>

                                    <td>
                                        <?php echo $item->getDataCadastro(); ?>
                                    </td>

                                    <td>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'editar', 'id' => $item->getId())); ?>" class="btn btn-xs btn-default permissao_remover"><span class="glyphicon glyphicon-pencil"></span></a>
                                        <a href="<?php echo $this->url($this->routeController, array('action' => 'remover', 'id' => $item->getId())); ?>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>

                    <?php
                    echo $this->paginationControl($this->registros, 'Sliding', 'partial/paginator', array('route' => $this->routeController));
                    ?>

                </div>

            </div>
        </div>
    </div>

</div>