<script src="<?php echo $this->basePath(); ?>/front/js/maps/gmap3.js"></script>         
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&key=AIzaSyANmgVkU2_FlRLVhhgIV8qxwDc_apeNgoY"></script>

<section class="title-section">
<div class="container">

<div class="row title">

<div class="col-md-9">
<h1>Cooperada
</h1>
</div>

</div>

</div>
</section>


<section class="paddings">
<div class="container">
<div class="row">

<div class="col-md-8">

<article class="post">
<h2><a href="#"><?php echo $cooperada->getNome(); ?></a></h2>

<div class="clearfix"></div>

<div class="info-post">
    <?php echo $cooperada->getTexto(); ?>
</div>
<hr>
<div id="map" class="mapping"></div>

<script type="text/javascript">
        var imagens = [];
        
        imagens[<?= $cooperada->getId() ?>] = '<img src="/gestao/bloco-home/imagem?image=cooperativas/<?php echo $cooperada->getImagem(); ?>&x=150&y=150" alt="<?php echo $cooperada->getNome() ?>">';

        var mapMarkers = [
            
            {
                address: "<?= $cooperada->getEndereco() ?>",
                html: imagens[<?= $cooperada->getId() ?>],
                icon: {
                    
                    image: "<?php echo $this->basePath(); ?>/front/img/pin.png",
                    iconsize: [26, 46],
                    iconanchor: [12, 46]
                }
            }

        ];

        // Map Initial Location
        var initLatitude = -19.9166813;
        var initLongitude = -43.9344931;

        // Map Extended Settings
        var mapSettings = {
            controls: {
                panControl: true,
                zoomControl: true,
                mapTypeControl: true,
                scaleControl: true,
                streetViewControl: true,
                overviewMapControl: true
            },
            scrollwheel: false,
            markers: mapMarkers,
            latitude: initLatitude,
            longitude: initLongitude,
            zoom: 6
        };
        
        $("#map").gMap(mapSettings);

        // Map Center At
        var mapCenterAt = function(options, e) {
            e.preventDefault();
            $("#map").gMap("centerAt", options);
        }

    </script>



</article>

</div>

<div class="col-md-4 sidebars">

<aside>
    <h4>Outras Cooperativas</h4>
    <ul class="list">
    <?php foreach($this->cooperadas as $cooperativa) {?>
        <li><i class="fa fa-check"></i><a href="<?php echo $this->url('consorciadas_front', array('action' => 'detalhes', 'id' => $cooperativa->getId())); ?>"><?php echo $cooperativa->getNome(); ?></a></li>
    <?php }?>
    </ul>
</aside>

<hr>

</div>

</div>
</div>

</section>

</div>