<?php $dadosUser = $this->DadosUser(); ?>


<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->titulo ?></h2>
    </div>
    <div class="col-lg-">
        <div class="ibox float-e-">

            <div class="ibox-">
                <div class="panel- col-lg-">

                    <?php if ($this->erro) { ?>
                        <div id="alert-message">
                            <div class="alert alert-danger alert-block fade in">
                                <button type="button" class="close" data-dismiss="alert">×</button>Verifique os erros.
                            </div>
                        </div>
                    <?php } ?>

                    <?php
                    $this->form->prepare();
                    if ($this->registro) {
                        $this->form->setAttribute('action', $this->url('nucleos', array('action' => 'editar', 'id' => $this->registro->getId())));
                    } else {
                        $this->form->setAttribute('action', $this->url('nucleos', array('action' => 'novo')));
                    }
                    ?>

                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php
                    echo $this->formHidden($this->form->get('id'));
                    echo $this->formElement($this->form->get('csrf'));
                    ?>

                    <div class="panel blank-panel" >
                        <div class="panel-body" style="margin-left: 15px">
                            <div class="tab-content">

                                <div class="tab-pane active" id="tab-1">
                                    

                                    <div class="form-group">
                                        <label>Projeto: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formSelect($this->form->get('projeto'));
                                        echo $this->formElementErrors()->render($this->form->get('projeto'));
                                        ?>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Mostrar núcleo no Site? </label>
                                        <?php
                                        echo $this->formCheckBox($this->form->get('status'));
                                        echo $this->formElementErrors()->render($this->form->get('status'));
                                        ?>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Nome: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('nome'));
                                        echo $this->formElementErrors()->render($this->form->get('nome'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label>Descrição: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('descricao'));
                                        echo $this->formElementErrors()->render($this->form->get('descricao'));
                                        ?>
                                    </div>


                                    <div class="form-group">
                                        <label>e-mail: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('email'));
                                        echo $this->formElementErrors()->render($this->form->get('descricao'));
                                        ?>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label>e-mail coorporativo: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('coorporativo'));
                                        echo $this->formElementErrors()->render($this->form->get('coorporativo'));
                                        ?>
                                    </div>
                                    

                                    <div class="form-group">
                                        <label>Telefone: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('telefone'));
                                        echo $this->formElementErrors()->render($this->form->get('telefone'));
                                        ?>
                                    </div>



                                    <div class="form-group">
                                        <label>Posição do Link: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('posicao'));
                                        echo $this->formElementErrors()->render($this->form->get('posicao'));
                                        ?>
                                    </div>



                                    <div class="form-group">
                                        <label>Texto: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formTextArea($this->form->get('texto'));
                                        echo $this->formElementErrors()->render($this->form->get('texto'));
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        
                                        
                                        <label>Imagem: <span class="required">*</span></label>
                                        <?php
                                        echo $this->formInput($this->form->get('imagem'));
                                        echo $this->formElementErrors()->render($this->form->get('imagem'));
                                        ?>
                                        <div class="alert alert-warning">
                                            Tamanho: 270px por 88px
                                        </div>
                                    </div>

                                    <div class="form-group permissao_add permissao_editar">
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                                name="salvar" value="1" style="margin-left: 15px">
                                            <strong>Salvar</strong>
                                        </button>
                                    </div>


                                </div>

                            </div>

                        </div>
                    </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
