<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Confirmação</title>
    </head>
    <body>

        <h2>
            Contato feito pelo site.
        </h2>

        <strong>Nome:</strong> <?php echo $this->dados['nome'] ?>
        <br><br>

        <strong>e-mail:</strong> <?php echo $this->dados['email'] ?>
        <br><br>

        <strong>Telefone:</strong> <?php echo $this->dados['telefone'] ?>
        <br><br>

        <strong>UF:</strong> <?php echo $this->dados['estado'] ?>
        <br><br>

        <strong>Mensagem:</strong> <?php echo $this->dados['mensagem'] ?>
        <br><br>
    </body>
</html>