<?php
$dadosUser = $this->DadosUser();
?>

<!DOCTYPE html>
<html>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php
        $NAME_APPLICATION = 'Fecoagro Leite Minas';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        ?>

        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="<?php echo $this->basePath(); ?>/css/animate.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/custom.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/bootstrap-colorpicker.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/js/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/switchery/switchery.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/plugins/chosen/chosen.css" rel="stylesheet">
        <link href="<?php echo $this->basePath(); ?>/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">

        <script src="<?php echo $this->basePath(); ?>/js/jquery-2.1.1.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/plugins/jquery-ui/jquery-ui.min.js"></script>

        <script src="<?php echo $this->basePath(); ?>/js/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        
        <script src="<?php echo $this->basePath(); ?>/ckeditor/ckeditor.js"></script>
        <script src="<?php echo $this->basePath(); ?>/ckfinder/ckfinder.js"></script>

    </head>

    <body>

        <div id="wrapper">

            <nav class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">

                        <li class="nav-header">
                            <div class="dropdown profile-element">
                            <img src="<?php echo $this->basePath(); ?>/front/img/logo-admin.png">
                            </div>
                            <div class="logo-element">
                                Fecoagro Leite Minas
                            </div>
                        </li>

                        <?php
                        $urlsLoja = array(
                           
                            $this->url('instituicao'),
                            $this->url('noticias'),
                            $this->url('videos'),
                        );
                        ?>

                        <li id="categoria_loja" class="<?php echo $this->menuAtivo($urlsLoja); ?>">
                            <a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Institucional</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="<?php echo $this->url('instituicao', array('action' => 'index')) ?>">Páginas Institucionais</a></li>
                                
                                
                            </ul>
                        </li>  

                        
                        
                     <?php
                $urlsMarketing = array(
                    $this->url('newsletter'),
                    $this->url('banners'),
                    $this->url('noticias'),
                );
                ?>
                
                    <li id="categoria_marketing" class="<?php echo $this->menuAtivo($urlsMarketing); ?>">
                        <a href="#"><i class="fa fa-envelope"></i> <span class="nav-label">Marketing</span><span
                                    class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse out" aria-expanded="false">

                            <li><a href="<?php echo $this->url('noticias', array('action' => 'index')) ?>">Notícias</a></li>
                            <li><a href="<?php echo $this->url('videos', array('action' => 'index')) ?>">Vídeos</a></li>
                            <li class="area_banners"><a
                                        href="<?php echo $this->url('banners', array('action' => 'index')) ?>">Banners</a>
                            </li>
                            <li class="area_newsletter"><a
                                        href="<?php echo $this->url('newsletter', array('action' => 'index')) ?>">Newsletter</a>
                            </li>
                            
                        </ul>
                    </li>
                
                        <?php
                        $urlsLoja = array(
                            $this->url('cooperativas'),
                            $this->url('regioes'),
                        );
                        ?>

                        <li id="categoria_loja" class="<?php echo $this->menuAtivo($urlsLoja); ?>">
                            <a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Cooperativas</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="<?php echo $this->url('cooperativas', array('action' => 'index')) ?>">Consorciadas</a></li>
                                <li><a href="<?php echo $this->url('regioes', array('action' => 'index')) ?>">Regiões</a></li>
                            </ul>
                        </li>
                        
                        
                        <?php
                        $urlsLoja = array(
                            $this->url('usuarios'),
                            $this->url('documentos'),
                            $this->url('agenda'),
                            $this->url('perfis'),
                            $this->url('categorias'),
                        );
                        ?>

                        <li id="categoria_loja" class="<?php echo $this->menuAtivo($urlsLoja); ?>">
                            <a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Intranet</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">
                                <li><a href="<?php echo $this->url('documentos', array('action' => 'index')) ?>">Arquivos</a></li>
                                <li><a href="<?php echo $this->url('agenda', array('action' => 'index')) ?>">Agenda e eventos</a></li>
                                <li><a href="<?php echo $this->url('usuarios', array('action' => 'index')) ?>">Usuários</a></li>
                                <li><a href="<?php echo $this->url('categorias', array('action' => 'index')) ?>">Categorias</a></li>
                                <li><a href="<?php echo $this->url('perfis', array('action' => 'index')) ?>">Perfis</a></li>
                            </ul>
                        </li>
    
                        <?php
                        $urlsAdmins = array(
                            $this->url('admin'),
                        );
                        ?>

                        <li id="categoria_admin" class="<?php echo $this->menuAtivo($urlsAdmins); ?>">
                            <a href="#"><i class="fa fa-user"></i> <span class="nav-label">Administração</span><span  class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse out" aria-expanded="false">

                                <li class="area_admin"><a href="<?php echo $this->url('admin', array('action' => 'index')) ?>">Administradores</a></li>

                            </ul>
                        </li>

                    </ul>

                </div>
            </nav>

            <div id="page-wrapper" class="gray-bg">

                <!-- Tool bar rop -->

                <div class="row border-bottom">
                    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                        <div class="navbar-header">
                            <span minimaliza-sidebar></span>
                            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i
                                    class="fa fa-bars"></i> </a>
                        </div>

                        <ul class="nav navbar-top-links navbar-right">

                            <li>
                                <a href="<?php echo $this->url('admin', array('action' => 'senha')); ?>">
                                    <i class="fa fa-gear"></i> Alterar Senha
                                </a>
                            </li>

                            <li>
                                <a href="<?php echo $this->url('login', array('action' => 'sair')); ?>">
                                    <i class="fa fa-sign-out"></i> Sair
                                </a>
                            </li>

                        </ul>

                    </nav>
                </div>

                <div>
                    <div class="row wrapper border-bottom white-bg page-heading">

                        <div class="row" style="clear: both; margin: 0 14px">

                            <div style="padding: 0 0 20px 0"><?php echo $this->content; ?></div>
                        </div>
                    </div>

                </div>
            </div>
            <script src="<?php echo $this->basePath(); ?>/js/inspinia.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/plugins/datapicker/bootstrap-datepicker.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/plugins/pace/pace.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/plugins/iCheck/icheck.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/jquery.mask.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/plugins/switchery/switchery.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/jquery.word-and-character-counter.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/plugins/chosen/chosen.jquery.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/jquery.magnific-popup.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/jquery.multi-select.js" type="text/javascript"></script>
            <script src="<?php echo $this->basePath(); ?>/js/bootstrap-colorpicker.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/custom.js?ijf=22"></script>

    </body>

</html>