<?php
$formLogin = $this->FormLogin();
$dadosUser = $this->dadosUserFront();
$em = $this->getEm();

$institucionais = $em->getRepository("Institucional\Entity\Instituicao")->listagemHome();
?>

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Basic -->
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>SÍTIO JONOSAKE</title>
                <!-- Bootstrap -->
                <link href="<?php echo $this->basePath(); ?>/front/css/bootstrap.min.css" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/front/css/styles.css" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/front/css/header-logo-center.css" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/front/css/footer-regular.css" rel="stylesheet">
                <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/front/css/animate.css"/>

                <!-- Fonts -->
                <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,300italic,700,700italic,600italic,800,800italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
                <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
                <link href="https://fonts.googleapis.com/css?family=Atma" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/front/css/font-awesome.min.css" rel="stylesheet">

                <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
                <!-- (necessary for Animation scroll) -->
                <script src="<?php echo $this->basePath(); ?>/front/js/jquery.viewportchecker.js"></script>
                <script src="<?php echo $this->basePath(); ?>/front/js/jquery.viewportchecker-effect.js"></script>

                <!-- Gallery Fancybox -->
                <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/front/css/jquery.fancybox.css">

                <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                <![endif]-->

    </head>
    <body> 

 
    <!-- layout-->
    <div id="wrapper" class="wrapper clearfix">


    <header id="header-logo-centered" class="header header-logo-centered clearfix">
        <div class="nav-top nav-top-info clearfix">
            <div class="col-md-12 col-sm-12 col-xs-12 text-left">
                <div class="text text-upper">
                    <strong>Reservas, dúvidas e contato</strong>
                </div>
                <div class="button">
                    <a href="#"><span>PORTAL DO GUIA</span></a>
                </div>
                <div class="contacts">
                    <span><i class="fa fa-envelope-o" aria-hidden="true"></i>sitiojonosake@sitiojonosake.com.br</span>
                    <span><i class="fa fa-phone" aria-hidden="true"></i>(21) 2687-8000</span>
                    <span>(21) 2687-8053</span>
                    <span>(21) 2687-8049</span>
                </div>
            </div>
        </div>
        <!-- END nav-top -->

        <div class="header-bottom">
            <div class="container text-center">
                <a href="http://www.jonosake.com.br/" class="navbar-brand col-xs-10">
                    <img src="<?php echo $this->basePath(); ?>/front/images/logo.png" width=250" alt="SÍTIO JONOSAKE" class="img-responsive center-block logo">
                </a>
            </div>


        </div>
        <!-- END header-bottom -->

        <div class="header-top">
            <div class="">
                <div class="socials">
                    <ul class="social-links2">
                        <li class="social">
                            <a href="https://www.facebook.com/www.sitiojonosake.com.br/" class="facebook " target="_blank"></a>
                        </li>
                        <li class="social">
                            <a href="https://www.instagram.com/jonosake/" class="instagram" target="_blank"></a>
                        </li>
                    </ul>
                </div>
                <!-- END socials-box -->
            </div>
            <!-- END col-md-3 -->


            <div class="container container-sticky visible-sm visible-xs">
                <div class="col-md-12 col-sm-12 col-xs-12 col-nav-section clearfix">
                    <nav class="hkiddo-nav  navbar navbar-default">
                        <div class="fluid">

                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header ">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Menu mobile</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div id="navbar" class="nav collapse navbar-collapse ">
                                <!-- MENU MOBILE -->
                                <ul id="menu-main" class="nav navbar-nav navbar-left">




                                    <li class="dropdown ">
                                        <a href="http://www.jonosake.com.br/">HOME</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">O JONOSAKE <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <!--<li><a href="http://www.jonosake.com.br/estrutura">ESTRUTURA /
                                                ATRAÇÕES</a></li>-->
                                            <li><a href="http://www.jonosake.com.br/historia">NOSSA HISTÓRIA</a>
                                            </li>
                                            <li><a href="http://www.jonosake.com.br/fotos">FOTOS</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">O DIA NO SÍTIO <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="http://www.jonosake.com.br/o-dia-no-sitio-jonosake">PROGRAMAÇÃO
                                                REGULAR</a></li>
                                            <li><a href="http://www.jonosake.com.br/excursoes-escolares-jonosake">EXCURSÕES
                                                ESCOLARES</a></li>
                                        </ul>
                                    </li>
                                    <!--<li class="dropdown ">
                                        <a href="http://www.jonosake.com.br/organize-sua-excursao">ORGANIZE SUA EXCURSÃO</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">FALE CONOSCO <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="http://www.jonosake.com.br/contato">CONTATO</a></li>
                                            <li><a href="http://www.jonosake.com.br/como-chegar-jonosake">COMO CHEGAR</a>
                                            </li>
                                            <li><a href="http://www.jonosake.com.br/perguntas-frequentes">PERGUNTAS
                                                FREQUENTES</a></li>
                                        </ul>
                                    </li>-->
                                    <li class="dropdown">
                                        <a href="http://www.jonosake.com.br/contato">FALE CONOSCO</a>
                                    </li>







                                    <!--<li class="dropdown ">
                                        <a href="http://www.jonosake.com.br/guias">PORTAL DO GUIA</a>
                                    </li>-->

                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- END col-md-9 -->
                <div class="sticky-logo">
                    <a href="http://www.jonosake.com.br/">
                        <img src="<?php echo $this->basePath(); ?>/front/images/logo.png" alt="SÍTIO JONOSAKE" class="img-responsive logo">
                    </a>
                </div>
                <!-- END sticky-logo -->
                <!-- END col-md-3 -->
            </div>
            <!-- END container container-sticky -->


            <div class="container container-sticky hidden-sm hidden-xs">
                <div class="col-md-12 col-sm-12 col-xs-12 col-nav-section clearfix">
                    <nav class="hkiddo-nav  navbar navbar-default">
                        <div class="fluid">

                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header ">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div id="navbar" class="nav collapse navbar-collapse ">

                                <ul id="menu-main" class="nav navbar-nav navbar-left">


                                    <li class="dropdown ">
                                        <a href="http://www.jonosake.com.br/">HOME</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">O JONOSAKE <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <!--<li><a href="http://www.jonosake.com.br/estrutura">ESTRUTURA /
                                                ATRAÇÕES</a></li>-->
                                            <li><a href="http://www.jonosake.com.br/historia">NOSSA HISTÓRIA</a>
                                            </li>
                                            <li><a href="http://www.jonosake.com.br/fotos">FOTOS</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">O DIA NO SÍTIO <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="http://www.jonosake.com.br/o-dia-no-sitio-jonosake">PROGRAMAÇÃO
                                                REGULAR</a></li>
                                            <li><a href="http://www.jonosake.com.br/excursoes-escolares-jonosake">EXCURSÕES
                                                ESCOLARES</a></li>
                                        </ul>
                                    </li>
                                    <!--<li class="dropdown ">
                                        <a href="http://www.jonosake.com.br/organize-sua-excursao">ORGANIZE SUA EXCURSÃO</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-haspopup="true" aria-expanded="true">FALE CONOSCO <span
                                                class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="http://www.jonosake.com.br/contato">CONTATO</a></li>
                                            <li><a href="http://www.jonosake.com.br/como-chegar-jonosake">COMO CHEGAR</a>
                                            </li>
                                            <li><a href="http://www.jonosake.com.br/perguntas-frequentes">PERGUNTAS
                                                FREQUENTES</a></li>
                                        </ul>
                                    </li>-->
                                    <li class="dropdown">
                                        <a href="http://www.jonosake.com.br/contato">FALE CONOSCO</a>
                                    </li>




                                </ul>

                            </div>
                        </div>
                    </nav>
                </div>
                <!-- END col-md-9 -->
                <div class="col-md-12 col-sm-12 col-xs-12col-links-section clearfix">
                    <div class="sticky-logo">
                        <a href="http://www.jonosake.com.br/">
                            <img src="<?php echo $this->basePath(); ?>/front/images/logo.png" alt="SÍTIO JONOSAKE" class="img-responsive logo">
                        </a>
                    </div>
                    <!-- END sticky-logo -->
                </div>
                <!-- END col-md-3 -->
            </div>
            <!-- END container container-sticky -->
        </div>
        <!-- END header-top -->
        <!-- <?php foreach($institucionais as $pagina) {?>                        
            <li><a href="<?php echo $this->url('institucional_front', array('action' => 'pagina', 'id' => $pagina->getId())); ?>"><?php echo $pagina->getNome() ?></a></li>
        <?php }?>
        <a href="<?php echo $this->url('eventos_front', array('action' => 'index')) ?>">EVENTOS </a> -->

    </header>
    <!-- END HEADER -->





        <?php echo $this->content ?>

        <footer class="footer-regular clearfix">
            <div class="first-row clearfix">
                <span class="decor"></span>

                <div class="container">
                    <div class="footer-widget col-md-3 col-sm-3 col-xs-12">
                        <h2>SÍTIO JONOSAKE</h2>
                        <ul>
                            <li><a href="http://www.jonosake.com.br/">HOME</a></li>
                            <!--<li><a href="http://www.jonosake.com.br/estrutura">ESTRUTURA / ATRAÇÕES</a></li>-->
                            <li><a href="http://www.jonosake.com.br/historia">NOSSA HISTÓRIA</a></li>
                            <li><a href="http://www.jonosake.com.br/fotos">FOTOS </a></li>
                            <li><a href="http://www.jonosake.com.br/o-dia-no-sitio-jonosake">O DIA NO SÍTIO </a></li>
                            <li><a href="http://www.jonosake.com.br/excursoes-escolares-jonosake">EXCURSÕES ESCOLARES </a></li>
                            <!--<li><a href="http://www.jonosake.com.br/organize-sua-excursao">ORGANIZE SUA EXCURSÃO </a></li>-->
                            <!--<li><a href="http://www.jonosake.com.br/guias">PORTAL DO GUIA </a></li>-->

                            <li><a href="http://www.jonosake.com.br/contato">CONTATO </a></li>
                        </ul>
                    </div>
                    <!-- end .footer-widget -->
                    <div class="footer-widget recent-works-widget col-md-3 col-sm-3 col-xs-12">
                        <h2 class="hidden-xs">FALE CONOSCO</h2>

                        <div class="contacts">
                            <div><i class="fa fa-map-marker" aria-hidden="true"></i> R. Norma Okasaki Inoue, 23 <br>
                                Santa Candida, Itaguaí - RJ
                                <br> CEP: 23821-590<br><br>
                            </div>
                            <div class="tel_rodape"><a href="tel:02126878000"><i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8000</a></div>
                            <div class="tel_rodape"><a href="tel:02126878053"><i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8053</a></div>
                            <div class="tel_rodape"><a href="tel:02126878049"><i class="fa fa-phone" aria-hidden="true"></i> (21) 2687-8049</a></div>
                            <div><i class="fa fa-envelope-o" aria-hidden="true"></i> sitiojonosake@sitiojonosake.com.br
                            </div>
                        </div>

                        <!--<ul>
                            <li><a href="http://www.jonosake.com.br/contato">CONTATO </a></li>
                            <li><a href="http://www.jonosake.com.br/como-chegar-jonosake">COMO CHEGAR </a></li>
                            <li><a href="http://www.jonosake.com.br/perguntas-frequentes">PERGUNTAS FREQUENTES </a></li>
                        </ul>-->

                    </div>
                    <!-- end .footer-widget.recent-works-widget -->
                    <div class="footer-widget social-box col-md-3 col-sm-3 col-xs-12">
                        <h2  class="hidden-xs">#JONOSAKE</h2>
                        <ul class="clearfix">
                            <li class="social">
                                <a href="https://www.facebook.com/www.sitiojonosake.com.br/" class="facebook " target="_blank"><i class="fa fa-facebook"
                                                                                 aria-hidden="true"></i></a>
                            </li>
                            <li class="social">
                                <a href="https://www.instagram.com/jonosake/" class="googleplus" target="_blank"><i class="fa fa-instagram"
                                                                                  aria-hidden="true"></i></a>
                            </li>
                        </ul>

                    </div>
                    <!-- end .footer-widget .services-widget -->

                    <div class="logo-box footer-widget col-height col-md-3 col-sm-3 col-xs-12">
                        <a href="http://www.jonosake.com.br/" class="">
                            <img src="<?php echo $this->basePath(); ?>/front/images/logo_rodape.png" alt="SÍTIO JONOSAKE" class="img-responsive logo">
                        </a>

                        <p class="copyright">Estância Turística Jonosake © 2017.<br>Todos os direitos reservados.</p>
                        <p class="copyright">Desenvolvido por <a href="http://www.webnativa.net" target="_blank">Web Nativa</a></p>
                    </div>
                    <!-- end .logo-box -->


                </div>
                <!-- end .container -->
            </div>
            <!-- end .first-row -->

        </footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87786542-1', 'auto');
  ga('send', 'pageview');

</script>


            <a href="#0" class="scroll-page back-to-top">
                <i class="fa fa-chevron-up" aria-hidden="true"></i>
            </a>


        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="<?php echo $this->basePath(); ?>/front/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/front/js/custom.js"></script>

        <!-- Masonry Isotop -->
        <script src="<?php echo $this->basePath(); ?>/front/js/isotope.pkgd.min.js"></script>
        <script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
        <!-- Gallery Fancybox -->
        <script src="<?php echo $this->basePath(); ?>/front/js/jquery.fancybox.pack.js"></script>
        <script src="<?php echo $this->basePath(); ?>/front/js/main-fancybox.js"></script>
    </body>
    </html>